services:
  - type: web
    name: real-lingo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn lingo_project.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: lingo_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: real-lingo-db
          property: connectionString
databases:
  - name: real-lingo-db
    plan: free
