# Generated by Django 4.2.21 on 2025-05-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        help_text="The original term or phrase in its native language.",
                        max_length=255,
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        help_text="Language code (e.g., 'en', 'es', 'de-BE' for regional German).",
                        max_length=15,
                    ),
                ),
                (
                    "region_code",
                    models.CharField(
                        blank=True,
                        help_text="Specific region if applicable (e.g., 'US-NY', 'Berlin', 'AU-NSW').",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SLANG", "Slang"),
                            ("IDIOM", "Idiom"),
                            ("SAYING", "Saying"),
                            ("TWISTER", "Tongue Twister"),
                            ("INSULT", "Insult (Colloquial)"),
                            ("WORD", "Unique Word"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of lingo entry (Slang, Idiom, Twister, etc.).",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "part_of_speech",
                    models.CharField(
                        blank=True,
                        help_text="Grammatical part of speech if applicable (e.g., 'noun', 'verb').",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="General cultural notes, etymology, or usage context.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the entry was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the entry was last updated.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entries",
            },
        ),
    ]
