# Generated by Django 4.2.21 on 2025-05-08 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_language_code",
                    models.CharField(
                        help_text="Language code for the translation (e.g., 'en', 'es').",
                        max_length=15,
                    ),
                ),
                (
                    "translation",
                    models.TextField(help_text="Main translation of the entry."),
                ),
                (
                    "literal_translation",
                    models.TextField(
                        blank=True, help_text="Optional literal translation.", null=True
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="entries.entry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentence",
                    models.TextField(help_text="Example sentence using the entry."),
                ),
                (
                    "language_code",
                    models.CharField(
                        help_text="Language code of the example sentence.",
                        max_length=15,
                    ),
                ),
                (
                    "translation",
                    models.TextField(
                        blank=True,
                        help_text="Optional translation of the example sentence.",
                        null=True,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="entries.entry",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entry",
            name="tags",
            field=models.ManyToManyField(blank=True, to="entries.tag"),
        ),
    ]
