# Generated by Django 4.2.21 on 2025-05-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0002_tag_translation_example_entry_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SLANG", "Slang (General)"),
                    ("YOUTH_SLANG", "Youth Slang"),
                    ("URBAN_SLANG", "Urban Slang"),
                    ("REGIONAL_SLANG", "Regional Slang"),
                    ("INTERNET_SLANG", "Internet Slang"),
                    ("JARGON", "Jargon"),
                    ("IDIOM", "Idiom / Phrase"),
                    ("PROVERB", "Proverb / Saying"),
                    ("INSULT", "Insult / Banter"),
                    ("JOKE", "Joke"),
                    ("WORDPLAY", "Wordplay / Pun"),
                    ("TONGUE_TWISTER", "Tongue Twister"),
                    ("FILLER_WORD", "Filler Word / Interjection"),
                    ("SHORTCUT", "Shortcut / Reduction"),
                    ("UNIQUE_CONCEPT", "Unique Concept / Word"),
                    ("CULTURAL_REFERENCE", "Cultural Reference"),
                    ("GREETING_FAREWELL", "Greeting / Farewell"),
                    ("ENDEARMENT", "Endearment / Address"),
                    ("OTHER", "Other"),
                ],
                help_text="Type of lingo entry (Slang, Idiom, Twister, etc.).",
                max_length=50,
                null=True,
            ),
        ),
    ]
