# Generated by Django 4.2.23 on 2025-06-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0003_alter_entry_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(
                default="#6c757d",
                help_text="Hex color code for tag display (e.g., #ff5733)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of what this tag represents",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Tag name (e.g., 'slang', 'formal', 'offensive')",
                max_length=50,
                unique=True,
            ),
        ),
    ]
