# Generated by Django 4.2.23 on 2025-06-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0005_userprogress_userfavorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slang", "Slang"),
                    ("insults", "Insults"),
                    ("tongue_twisters", "Tongue Twisters"),
                    ("colloquial_phrases", "Colloquial Phrases"),
                    ("jokes", "Jokes"),
                    ("unique_concepts", "Unique Concepts"),
                ],
                help_text="Standardized category type: slang, insults, tongue twisters, colloquial phrases, jokes, or unique concepts.",
                max_length=50,
                null=True,
            ),
        ),
    ]
