# Generated by Django 4.2.23 on 2025-06-18 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entries", "0006_alter_entry_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="User who contributed this entry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contributed_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
